[zh]
    languageCode      = "zh-cn"
    languageName      = "中文"
    languagedirection = "ltr"
    title             = "MowMark的个人博客"
    weight            = 1

# [en]
#     languageCode      = "en-us"
#     languageName      = "English"
#     languagedirection = "ltr"
#     title             = "MowMark's Blog"
#     weight            = 2
