[[main]]
    identifier = "home"
    name       = "首页"
    url        = "/"
    weight     = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "computer"
    name = "计算机"
    url = "/computer/"
    weight = 2
    [main.params]
        icon = "device-desktop"

[[main]]
    identifier = "robot"
    name = "机器人"
    url = "/robot/"
    weight = 5
    [main.params]
      icon = "robot"

[[main]]
    identifier = "website"
    name       = "网站"
    url        = "/website/"
    weight     = 6 
    [main.params]
        icon = "world-www"

[[main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 10
    [main.params]
        icon = "user"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/MowMark"
    weight = 1
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "bilibili"
    name = "BiliBili"
    url = "https://space.bilibili.com/35739912"
    weight = 2
    [social.params]
        icon = "brand-bilibili"

[[social]]
    identifier = "RSS"
    name       = "RSS"
    url        = "/index.xml"
    weight = 10
    [social.params]
        icon = "rss"
